import {Consumption} from "../entities/consumption";

export const ConsumptionSeed: Consumption[] = [

	// Bieren
	{name: "Stella", price: 1.80, category: {id: 1}},
	{name: "Jupiler", price: 1.80, category: {id: 1}},
	{name: "Jupiler Blue", price: 2, category: {id: 1}},
	{name: "Derijck", price: 1.80, category: {id: 1}},
	{name: "Palm", price: 2, category: {id: 1}},
	{name: "Vieux-Temps", price: 2, category: {id: 1}},
	{name: "Carlsberg", price: 2, category: {id: 1}},
	{name: "Hoegaarden", price: 2, category: {id: 1}},
	{name: "Adriaan Brouwer", price: 2, category: {id: 1}},
	{name: "Kriek Lindemans", price: 2, category: {id: 1}},
	{name: "Liefmans On The Rocks", price: 2, category: {id: 1}},
	{name: "Rodenbach", price: 2, category: {id: 1}},
	{name: "Strongbow", price: 3, category: {id: 1}},

	// Speciale Bieren
	{name: "Chimay Blauw", price: 3.50, category: {id: 2}},
	{name: "Orval", price: 4.00, category: {id: 2}},
	{name: "Corona", price: 3.00, category: {id: 2}},
	{name: "Flandriën", price: 3.50, category: {id: 2}},
	{name: "Cherry Chouffe", price: 3.50, category: {id: 2}},
	{name: "Zatte Rita Blond", price: 3.50, category: {id: 2}},
	{name: "Zatte Rita Bruin", price: 3.50, category: {id: 2}},
	{name: "Steenuilke", price: 3.50, category: {id: 2}},
	{name: "Karmeliet Tripel", price: 3.50, category: {id: 2}},
	{name: "Geuze Boon", price: 3.50, category: {id: 2}},
	{name: "Cornet", price: 3.50, category: {id: 2}},
	{name: "Gust", price: 3.50, category: {id: 2}},
	{name: "Arend Tripel", price: 3.50, category: {id: 2}},
	{name: "Westmalle", price: 3.50, category: {id: 2}},
	{name: "Rochefort", price: 3.50, category: {id: 2}},
	{name: "Duvel", price: 3.50, category: {id: 2}},
	{name: "Vedett", price: 3.50, category: {id: 2}},
	{name: "Kasteel Rouge", price: 3.50, category: {id: 2}},
	{name: "Ename Blond", price: 3.50, category: {id: 2}},
	{name: "Leffe Blond", price: 3.50, category: {id: 2}},
	{name: "Leffe Bruin", price: 3.50, category: {id: 2}},

	//Bieren 0%
	{name: "Jupiler 0,0%", price: 2.20, category: {id: 3}},
	{name: "Carlsberg 0,0%", price: 2.20, category: {id: 3}},

	// Frisdranken
	{name: "Cola", price: 1.80, category: {id: 4}},
	{name: "Cola Zero", price: 1.80, category: {id: 4}},
	{name: "Limonade", price: 1.80, category: {id: 4}},
	{name: "Tonisteiner Citroen", price: 2.00, category: {id: 4}},
	{name: "Gini", price: 2.00, category: {id: 4}},
	{name: "Schweppes", price: 2.00, category: {id: 4}},
	{name: "Schweppes Agrum", price: 2.00, category: {id: 4}},
	{name: "Ice-Tea", price: 2.00, category: {id: 4}},
	{name: "Looza", price: 2.00, category: {id: 4}},
	{name: "Red-Bull", price: 3.00, category: {id: 4}},
	{name: "Plat Water", price: 1.80, category: {id: 4}},
	{name: "Bruiswater", price: 1.80, category: {id: 4}},
	{name: "Chocomelk", price: 2.00, category: {id: 4}},

	// Wijnen
	{name: "Witte Wijn", price: 3.00, category: {id: 5}},
	{name: "Rode Wijn", price: 3.00, category: {id: 5}},
	{name: "Rosé Wijn", price: 3.00, category: {id: 5}},
	{name: "Cava", price: 3.50, category: {id: 5}},

	// Versnaperingen
	{name: "Chips", price: 1.90, category: {id: 6}},
	{name: "Partysnacks 32 stuks + sausje", price: 8.00, category: {id: 6}},
	{name: "Bitterballen 20 stuks + sausje", price: 8.00, category: {id: 6}},
	{name: "Calamares + verse huisgemaakte tartare", price: 10, category: {id: 6}},
	{name: "Frikandel 2 Stuks + sausje", price: 5, category: {id: 6}},
	{name: "Frikandel Speciale", price: 4, category: {id: 6}},
	{name: "Spaghetti groot", price: 9, category: {id: 6}},
	{name: "Spaghetti klein", price: 7, category: {id: 6}},
	{name: "Pizza Hawai", price: 8, category: {id: 6}},
	{name: "Pizza Bolognaise", price: 8, category: {id: 6}},
	{name: "Pizza Vegetarisch", price: 8, category: {id: 6}},

	// Warme Dranken
	{name: "Cappuccino", price: 3.00, category: {id: 7}},
	{name: "Koffie", price: 2.00, category: {id: 7}},
	{name: "Koffie verkeerd", price: 4.00, category: {id: 7}},
	{name: "Chocomelk", price: 4.00, category: {id: 7}},
	{name: "Thee", price: 2.00, category: {id: 7}},
	{name: "Kleine Koffie", price: 2.00, category: {id: 7}},
	{name: "Koffie + Sterke drank", price: 7.00, category: {id: 7}},
	{name: "Livinus Koffie", price: 4.00, category: {id: 7}},

	// Aperitieven
	{name: "Martini Wit", price: 4.00, category: {id: 8}},
	{name: "Maritini Rood", price: 4.00, category: {id: 8}},
	{name: "Martini Bellini", price: 4.00, category: {id: 8}},
	{name: "Porto Wit", price: 4.00, category: {id: 8}},
	{name: "Porto Rood", price: 4.00, category: {id: 8}},
	{name: "Sherry", price: 4.00, category: {id: 8}},
	{name: "Pinot Des Charentes", price: 4.00, category: {id: 8}},
	{name: "Amaretto", price: 4.00, category: {id: 8}},
	{name: "Cuarenta Y Tres \'43\'", price: 4.00, category: {id: 8}},
	{name: "Baileys", price: 4.00, category: {id: 8}},

	// Sterke Dranken
	{name: "Gordon gin + Fris", price: 7.00, category: {id: 9}},
	{name: "Hendrickx Gin + Fris", price: 9.00, category: {id: 9}},
	{name: "Vodka Wit + Fris", price: 7.00, category: {id: 9}},
	{name: "Vodka Rood + Fris", price: 7.00, category: {id: 9}},
	{name: "Aperol spritz", price: 7.00, category: {id: 9}},
	{name: "Wiskey", price: 5.00, category: {id: 9}},
	{name: "Cognac", price: 4.00, category: {id: 9}},
	{name: "Malibu", price: 5.00, category: {id: 9}},
	{name: "Elexir", price: 4.00, category: {id: 9}},
	{name: "Limoncello", price: 4.00, category: {id: 9}},
	{name: "Cointreau", price: 5.00, category: {id: 9}},
	{name: "Safari + Fris", price: 7.00, category: {id: 9}},
	{name: "Campari + Fris", price: 7.00, category: {id: 9}},
	{name: "Pisang + Fris", price: 7.00, category: {id: 9}},
	{name: "Bacardi Wit + Fris", price: 7.00, category: {id: 9}},
	{name: "Bacardi Bruin + Fris", price: 7.00, category: {id: 9}},
	{name: "Passoa + Fris", price: 7.00, category: {id: 9}},
	{name: "Ricard + Fris", price: 7.00, category: {id: 9}},
	{name: "Jenever natuur", price: 4.00, category: {id: 9}},
	{name: "Jenever Vanille", price: 4.00, category: {id: 9}},
	{name: "Jenever Choco", price: 4.00, category: {id: 9}},
];